#!/usr/bin/env python3
"""Reproducibly narrow dist's generated workflow. No hosted actions or releases.

Upstream does not expose permissions for built-in jobs or an option to omit its
empty announce job. Keep packaging upstream-generated and limit modifications to
these security/cost choices. Requires dist 0.33.0 and Python 3.11+.
"""
import argparse
import os
from pathlib import Path
import subprocess

parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
os.chdir(Path(__file__).resolve().parent.parent)
path = Path('.github/workflows/release.yml')
original = path.read_bytes() if path.exists() else None
config = Path('dist-workspace.toml')
config_original = config.read_bytes()
try:
    config.write_bytes(config_original.replace(b'allow-dirty = ["ci"]', b'allow-dirty = []'))
    subprocess.run([os.environ.get('DIST', 'dist'), 'generate', '--mode=ci'], check=True)
    text = path.read_text()
    assert '  announce:\n' in text and '  "contents": "write"' in text
    text = text.replace('runs-on: "ubuntu-22.04"', 'runs-on: "ubuntu-24.04"')
    text = text.split('\n  announce:\n')[0] + '\n'
    text = text.replace('  "contents": "write"', '  contents: read', 1)
    text = text.replace("      - '**[0-9]+.[0-9]+.[0-9]+*'", "      - 'v[0-9]+.[0-9]+.[0-9]+'")
    # No workflow-level token environment: installer/dependency scripts get no token.
    text = text.replace('    env:\n      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}\n', '    env:\n')
    text = text.replace('    env:\n    steps:', '    steps:')
    text = text.replace('    env:\n    runs-on:', '    runs-on:')
    text = text.replace('  host:\n', '  host:\n    permissions:\n      contents: write\n')
    # Planning is read-only; do not create a draft release just to compute a matrix.
    old = "dist ${{ (!github.event.pull_request && format('host --steps=create --tag={0}', github.ref_name)) || 'plan' }}"
    assert old in text
    text = text.replace(old, 'dist plan --tag="$RELEASE_TAG"')
    text = text.replace('      - id: plan\n        run:', '''      - id: plan
        env:
          RELEASE_TAG: ${{ github.ref_name }}
        run:''')
    text = text.replace('          dist plan --tag="$RELEASE_TAG"', '''          python3 scripts/release-version.py "$RELEASE_TAG"
          dist plan --tag="$RELEASE_TAG"''')
    text = text.replace('      - id: host\n        shell:', '''      - id: host
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell:''')
    text = text.replace('      - name: Create GitHub Release\n        env:', '''      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}''')
    text = '# Generated by scripts/dist-workflow.py from dist 0.33.0. Do not edit manually.\n' + text
    path.write_text(text)
    if args.check and original != path.read_bytes():
        raise SystemExit('Release workflow differs; run python3 scripts/dist-workflow.py')
finally:
    config.write_bytes(config_original)
    if args.check:
        if original is None:
            path.unlink(missing_ok=True)
        else:
            path.write_bytes(original)
